  - alias: 'Office-temp under slider2 - 0.5'
    trigger:
      platform: state
      entity_id: sensor.office_humidity
    condition:
    - condition: template
      value_template: '{{ float(states.sensor.office_temperature.state) < float(states.input_slider.slider2.state) - 0.5 }}'
    action:
      service: homeassistant.turn_on
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_24_0
    
  - alias: 'Office-temp over slider2'
    trigger:
      platform: state
      entity_id: sensor.office_humidity
    condition:
    - condition: template
      value_template: '{{ float(states.sensor.office_temperature.state) > float(states.input_slider.slider2.state) }}'
    action:
      service: homeassistant.turn_off
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_24_0

  - alias: 'Living room-temp under slider1 - 0.5'
    trigger:
      platform: state
      entity_id: sensor.living_room_humidity
    condition:
    - condition: template
      value_template: '{{ float(states.sensor.living_room_temperature.state) < float(states.input_slider.slider1.state) - 0.5 }}'
    action:
      service: homeassistant.turn_on
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_28_0
      
  - alias: 'Living room-temp over slider1'
    trigger:
      platform: state
      entity_id: sensor.living_room_humidity
    condition:
    - condition: template
      value_template: '{{ float(states.sensor.living_room_temperature.state) > float(states.input_slider.slider1.state) }}'
    action:
      service: homeassistant.turn_off
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_28_0

  - alias: 'Alarm trigger notification'
    trigger:
      platform: state
      entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_25_0
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.set_alarm
      state: 'on'
    action:
      service: notify.pushbullet
      data:
        title: "Alarm triggered!"
        message: "{{ states.sensor.date__time.state }}"
 
  - alias: 'Set Living room night temp at 00:30'
    trigger: 
      platform: time
      after: "00:30:00" 
    condition:
    - condition: state
      entity_id: input_boolean.thermo_control
      state: 'on'
    action: 
      service: input_slider.select_value
      data_template:
        entity_id: input_slider.slider1
        value: '{{ states.input_slider.slider3.state }}'
  
  - alias: 'Set Office night temp at 00:30'
    trigger: 
      platform: time
      after: "00:30:00" 
    condition:
    - condition: state
      entity_id: input_boolean.thermo_control
      state: 'on'
    action: 
      service: input_slider.select_value
      data_template:
        entity_id: input_slider.slider2
        value: '{{ states.input_slider.slider3.state }}'

  - alias: 'Set Living room day temp at 07:00'
    trigger: 
      platform: time
      after: "07:00:00" 
    condition:
    - condition: state
      entity_id: input_boolean.thermo_control
      state: 'on'
    action: 
      service: input_slider.select_value
      data_template:
        entity_id: input_slider.slider1
        value: 22.0

  - alias: 'Set Office day temp at 07:00'
    trigger: 
      platform: time
      after: "07:00:00" 
    condition:
    - condition: state
      entity_id: input_boolean.thermo_control
      state: 'on'
    action: 
      service: input_slider.select_value
      data_template:
        entity_id: input_slider.slider2
        value: 22.0
      
  - alias: 'Update Available Notifications'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: persistent_notification.create
      data:
        message: 'A new update for Home Assistant is available.'
        title: "Update now!"
  
  - alias: 'Nobody Home - Joachimleft'
    trigger:
      - platform: state
        entity_id: device_tracker.joachimsiphone6
        from: 'home' 
        to: 'not_home'  
    condition:
      condition: and
      conditions:
       - condition: state
         entity_id: device_tracker.joachimsiphone6
         state: 'not_home'
       - condition: state
         entity_id: device_tracker.slvisiphone
         state: 'not_home'
    action:
      service: homeassistant.turn_off
      entity_id:  group.lights  

  - alias: 'Nobody Home - Solvileft'
    trigger:
      - platform: state
        entity_id: device_tracker.slvisiphone
        from: 'home' 
        to: 'not_home'  
    condition:
      condition: and
      conditions:
       - condition: state
         entity_id: device_tracker.joachimsiphone6
         state: 'not_home'
       - condition: state
         entity_id: device_tracker.slvisiphone
         state: 'not_home'
    action:
      service: homeassistant.turn_off
      entity_id:  group.lights  
  
  - alias: Turn on Hall light when there is movement
    trigger:
      - platform: state
        entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_29_0
        to: 'on'
    condition:
       - condition: state
         entity_id: light.hall_light
         state: 'off'
    action:
      service: homeassistant.turn_on
      entity_id: script.timed_lamp
      
  - alias: Turn off Office light when there is no movement for 5 minute
    trigger:
      - platform: state
        entity_id: binary_sensor.office_motion
        to: 'off'
        for:
          minutes: 5
    condition:
       - condition: state
         entity_id: input_boolean.office_control
         state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: 
        - light.office
        - switch.office_window_light
        - switch.office_table_light
      
  - alias: Turn on Office light when there is movement
    trigger:
      - platform: state
        entity_id: binary_sensor.office_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.office_control
        state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: 
        - light.office
        - switch.office_window_light
        - switch.office_table_light
